# Generated by Django 6.0.7 on 2026-07-28 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_protection', models.BooleanField(default=True)),
                ('data_sharing', models.BooleanField(default=False)),
                ('ad_blocking', models.BooleanField(default=True)),
                ('cookie_control', models.BooleanField(default=True)),
                ('location_masking', models.BooleanField(default=False)),
                ('fingerprint_defense', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
